//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.LearningComponents.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchemaCompiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute {0} not found on element {1}.
        /// </summary>
        internal static string AttributeNotFound {
            get {
                return ResourceManager.GetString("AttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value not allowed for property {0} on item {1}..
        /// </summary>
        internal static string DefaultValueNotAllowed {
            get {
                return ResourceManager.GetString("DefaultValueNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; defined more than once..
        /// </summary>
        internal static string DuplicateIdentifier {
            get {
                return ResourceManager.GetString("DuplicateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element {0} not found.
        /// </summary>
        internal static string ElementNotFound {
            get {
                return ResourceManager.GetString("ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumName attribute not found for property {0} on item type {1}..
        /// </summary>
        internal static string EnumAttributeNotFoundForProperty {
            get {
                return ResourceManager.GetString("EnumAttributeNotFoundForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumName attribute not found for column {0} in view {1}..
        /// </summary>
        internal static string EnumAttributeNotFoundInColumn {
            get {
                return ResourceManager.GetString("EnumAttributeNotFoundInColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumName attribute not found for parameter {0} in right {1}..
        /// </summary>
        internal static string EnumAttributeNotFoundInRightParameter {
            get {
                return ResourceManager.GetString("EnumAttributeNotFoundInRightParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumName attribute not found for parameter {0} in view {1}..
        /// </summary>
        internal static string EnumAttributeNotFoundInViewParameter {
            get {
                return ResourceManager.GetString("EnumAttributeNotFoundInViewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} on item type {1} references an Enum {2} that does not exist..
        /// </summary>
        internal static string EnumTypeNotFoundForProperty {
            get {
                return ResourceManager.GetString("EnumTypeNotFoundForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} in view {1} references an Enum {2} that does not exist..
        /// </summary>
        internal static string EnumTypeNotFoundInColumn {
            get {
                return ResourceManager.GetString("EnumTypeNotFoundInColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} in right {1} references an Enum {2} that does not exist..
        /// </summary>
        internal static string EnumTypeNotFoundInRightParameter {
            get {
                return ResourceManager.GetString("EnumTypeNotFoundInRightParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} in view {1} references an Enum {2} that does not exist..
        /// </summary>
        internal static string EnumTypeNotFoundInViewParameter {
            get {
                return ResourceManager.GetString("EnumTypeNotFoundInViewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Contains schema-related constants.
        ///        &lt;/summary&gt;
        ///    .
        /// </summary>
        internal static string HelperBaseSchemaInternalClassDocumentation {
            get {
                return ResourceManager.GetString("HelperBaseSchemaInternalClassDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Contains constants related to the {0} item type.
        ///        &lt;/summary&gt;
        ///    .
        /// </summary>
        internal static string HelperBaseSchemaInternalItemTypeDocumentation {
            get {
                return ResourceManager.GetString("HelperBaseSchemaInternalItemTypeDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Maximum length of the {0} property in bytes.
        ///        &lt;/summary&gt;
        ///    .
        /// </summary>
        internal static string HelperBaseSchemaInternalItemTypePropertyMaximumLengthOfByteArray {
            get {
                return ResourceManager.GetString("HelperBaseSchemaInternalItemTypePropertyMaximumLengthOfByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Maximum length of the {0} property in characters.
        ///        &lt;/summary&gt;
        ///    .
        /// </summary>
        internal static string HelperBaseSchemaInternalItemTypePropertyMaximumLengthOfString {
            get {
                return ResourceManager.GetString("HelperBaseSchemaInternalItemTypePropertyMaximumLengthOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        {0} ({1}).
        ///    .
        /// </summary>
        internal static string HelperEnumValueSummary {
            get {
                return ResourceManager.GetString("HelperEnumValueSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        ///// This code was generated by a tool.
        /////
        ///// Changes to this file may cause incorrect behavior and will be lost if
        ///// the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///    .
        /// </summary>
        internal static string HelperHeader {
            get {
                return ResourceManager.GetString("HelperHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Create a new instance of the {0} class.
        ///        &lt;/summary&gt;
        ///        &lt;param name=&quot;key&quot;&gt;The unique integer value assigned to the item.  This must be a positive integer.&lt;/param&gt;
        ///        &lt;exception cref=&quot;System.ArgumentOutOfRangeException&quot;&gt;&lt;paramref name=&quot;key&quot;/&gt; is not a valid positive integer.&lt;/exception&gt;
        ///    .
        /// </summary>
        internal static string HelperIdentifierConstructor1Documentation {
            get {
                return ResourceManager.GetString("HelperIdentifierConstructor1Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Create a new instance of the {0} class.
        ///        &lt;/summary&gt;
        ///        &lt;param name=&quot;id&quot;&gt;Identifier that should be copied.&lt;/param&gt;
        ///        &lt;exception cref=&quot;System.ArgumentNullException&quot;&gt;&lt;paramref name=&quot;id&quot;/&gt; is a null refrence.&lt;/exception&gt;
        ///        &lt;exception cref=&quot;System.ArgumentOutOfRangeException&quot;&gt;&lt;paramref name=&quot;id&quot;/&gt; does not contain
        ///            a {1} identifier.&lt;/exception&gt;
        ///    .
        /// </summary>
        internal static string HelperIdentifierConstructor2Documentation {
            get {
                return ResourceManager.GetString("HelperIdentifierConstructor2Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Represents an identifier to a &lt;Typ&gt;{0}&lt;/Typ&gt; in a store.
        ///        &lt;/summary&gt;
        ///    .
        /// </summary>
        internal static string HelperIdentifierDocumentation {
            get {
                return ResourceManager.GetString("HelperIdentifierDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        The value stored in this property is generated automatically when a new item is
        ///        added.  It is unique across all items of the item type.
        ///    .
        /// </summary>
        internal static string HelperItemTypeIdPropertyRemarks {
            get {
                return ResourceManager.GetString("HelperItemTypeIdPropertyRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Name of the &lt;Typ&gt;{0}&lt;/Typ&gt; item type.
        ///        &lt;/summary&gt;
        ///    .
        /// </summary>
        internal static string HelperItemTypeNameDocumentation {
            get {
                return ResourceManager.GetString("HelperItemTypeNameDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Item will automatically be deleted when the referred-to item is deleted.
        ///    .
        /// </summary>
        internal static string HelperItemTypePropertyAutoDelete {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyAutoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Default value: {0}
        ///    .
        /// </summary>
        internal static string HelperItemTypePropertyDefault {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties on the item type:.
        /// </summary>
        internal static string HelperItemTypePropertyList {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Maximum length of the &lt;Fld&gt;{0}&lt;/Fld&gt; property in bytes.
        ///    .
        /// </summary>
        internal static string HelperItemTypePropertyMaximumLengthOfByteArray {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyMaximumLengthOfByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Maximum length of the &lt;Fld&gt;{0}&lt;/Fld&gt; property in characters.
        ///    .
        /// </summary>
        internal static string HelperItemTypePropertyMaximumLengthOfString {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyMaximumLengthOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Name of the {0} property on the &lt;Typ&gt;{1}&lt;/Typ&gt; item type.
        ///    .
        /// </summary>
        internal static string HelperItemTypePropertyNameSummary {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyNameSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Property does not have a default value.
        ///    .
        /// </summary>
        internal static string HelperItemTypePropertyNoDefault {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyNoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Property can not contain null.
        ///    .
        /// </summary>
        internal static string HelperItemTypePropertyNotNullable {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Property can contain null.
        ///    .
        /// </summary>
        internal static string HelperItemTypePropertyNullable {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Property type: {0}
        ///    .
        /// </summary>
        internal static string HelperItemTypePropertyType {
            get {
                return ResourceManager.GetString("HelperItemTypePropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Contains constants related to the {0} item type.
        ///    .
        /// </summary>
        internal static string HelperItemTypeSummary {
            get {
                return ResourceManager.GetString("HelperItemTypeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string HelperNone {
            get {
                return ResourceManager.GetString("HelperNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Name of the &lt;Typ&gt;{0}&lt;/Typ&gt; right.
        ///        &lt;/summary&gt;
        ///    .
        /// </summary>
        internal static string HelperRightNameDocumentation {
            get {
                return ResourceManager.GetString("HelperRightNameDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters in the right:.
        /// </summary>
        internal static string HelperRightParameterList {
            get {
                return ResourceManager.GetString("HelperRightParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Name of the {0} parameter on the &lt;Typ&gt;{1}&lt;/Typ&gt; right.
        ///    .
        /// </summary>
        internal static string HelperRightParameterNameSummary {
            get {
                return ResourceManager.GetString("HelperRightParameterNameSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Parameter type: {0}
        ///    .
        /// </summary>
        internal static string HelperRightParameterType {
            get {
                return ResourceManager.GetString("HelperRightParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Contains constants related to the {0} right.
        ///    .
        /// </summary>
        internal static string HelperRightSummary {
            get {
                return ResourceManager.GetString("HelperRightSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string HelperValueTypeBoolean {
            get {
                return ResourceManager.GetString("HelperValueTypeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByteArray[{0}].
        /// </summary>
        internal static string HelperValueTypeByteArray {
            get {
                return ResourceManager.GetString("HelperValueTypeByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByteArray[].
        /// </summary>
        internal static string HelperValueTypeByteArrayWithoutLength {
            get {
                return ResourceManager.GetString("HelperValueTypeByteArrayWithoutLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string HelperValueTypeDateTime {
            get {
                return ResourceManager.GetString("HelperValueTypeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string HelperValueTypeDouble {
            get {
                return ResourceManager.GetString("HelperValueTypeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Typ&gt;{0}&lt;/Typ&gt;.
        /// </summary>
        internal static string HelperValueTypeEnum {
            get {
                return ResourceManager.GetString("HelperValueTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string HelperValueTypeGuid {
            get {
                return ResourceManager.GetString("HelperValueTypeGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int32.
        /// </summary>
        internal static string HelperValueTypeInt32 {
            get {
                return ResourceManager.GetString("HelperValueTypeInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to a &lt;Typ&gt;{0}&lt;/Typ&gt; item type..
        /// </summary>
        internal static string HelperValueTypeItemIdentifier {
            get {
                return ResourceManager.GetString("HelperValueTypeItemIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string HelperValueTypeSingle {
            get {
                return ResourceManager.GetString("HelperValueTypeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String[{0}].
        /// </summary>
        internal static string HelperValueTypeString {
            get {
                return ResourceManager.GetString("HelperValueTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String[].
        /// </summary>
        internal static string HelperValueTypeStringWithoutLength {
            get {
                return ResourceManager.GetString("HelperValueTypeStringWithoutLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml.
        /// </summary>
        internal static string HelperValueTypeXml {
            get {
                return ResourceManager.GetString("HelperValueTypeXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns in the view:.
        /// </summary>
        internal static string HelperViewColumnList {
            get {
                return ResourceManager.GetString("HelperViewColumnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Name of the {0} column on the &lt;Typ&gt;{1}&lt;/Typ&gt; view.
        ///    .
        /// </summary>
        internal static string HelperViewColumnNameSummary {
            get {
                return ResourceManager.GetString("HelperViewColumnNameSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Column type: {0}
        ///    .
        /// </summary>
        internal static string HelperViewColumnType {
            get {
                return ResourceManager.GetString("HelperViewColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;summary&gt;
        ///        Name of the &lt;Typ&gt;{0}&lt;/Typ&gt; view.
        ///        &lt;/summary&gt;
        ///    .
        /// </summary>
        internal static string HelperViewNameDocumentation {
            get {
                return ResourceManager.GetString("HelperViewNameDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters in the view:.
        /// </summary>
        internal static string HelperViewParameterList {
            get {
                return ResourceManager.GetString("HelperViewParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Name of the {0} parameter on the &lt;Typ&gt;{1}&lt;/Typ&gt; view.
        ///    .
        /// </summary>
        internal static string HelperViewParameterNameSummary {
            get {
                return ResourceManager.GetString("HelperViewParameterNameSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Parameter type: {0}
        ///    .
        /// </summary>
        internal static string HelperViewParameterType {
            get {
                return ResourceManager.GetString("HelperViewParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Contains constants related to the {0} view.
        ///    .
        /// </summary>
        internal static string HelperViewSummary {
            get {
                return ResourceManager.GetString("HelperViewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; not found.
        /// </summary>
        internal static string IdentifierNotFound {
            get {
                return ResourceManager.GetString("IdentifierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid default value for property {0} on item type {1}.  Non-null default values are not permitted..
        /// </summary>
        internal static string InvalidDefaultForItemIdentifierProperty {
            get {
                return ResourceManager.GetString("InvalidDefaultForItemIdentifierProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid default value for property {0} on item type {1}..
        /// </summary>
        internal static string InvalidDefaultValue {
            get {
                return ResourceManager.GetString("InvalidDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid default value for property {0} on item type {1}: {2}.
        /// </summary>
        internal static string InvalidDefaultValueWithError {
            get {
                return ResourceManager.GetString("InvalidDefaultValueWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length attribute for property {0} on item type {1} must be between 1 and (Int32.Max-2)..
        /// </summary>
        internal static string InvalidLengthForByteArrayProperty {
            get {
                return ResourceManager.GetString("InvalidLengthForByteArrayProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length attribute for property {0} on item type {1} must be between 1 and (Int32.Max-2)/2..
        /// </summary>
        internal static string InvalidLengthForStringProperty {
            get {
                return ResourceManager.GetString("InvalidLengthForStringProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid default value of &apos;null&apos; for property {0} on item type {1}..
        /// </summary>
        internal static string NullDefaultForNonNullableProperty {
            get {
                return ResourceManager.GetString("NullDefaultForNonNullableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} on right {1} has already been defined..
        /// </summary>
        internal static string ParameterAlreadyDefinedInRight {
            get {
                return ResourceManager.GetString("ParameterAlreadyDefinedInRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} not found on right {1}..
        /// </summary>
        internal static string ParameterNotFoundInRight {
            get {
                return ResourceManager.GetString("ParameterNotFoundInRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} on item type {1} has already been defined..
        /// </summary>
        internal static string PropertyAlreadyDefined {
            get {
                return ResourceManager.GetString("PropertyAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} not found on item type {1}..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferencedItemTypeName attribute not found for property {0} on item type {1}..
        /// </summary>
        internal static string ReferencedItemTypeAttributeNotFoundForProperty {
            get {
                return ResourceManager.GetString("ReferencedItemTypeAttributeNotFoundForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferencedItemTypeName attribute not found for column {0} in view {1}..
        /// </summary>
        internal static string ReferencedItemTypeAttributeNotFoundInColumn {
            get {
                return ResourceManager.GetString("ReferencedItemTypeAttributeNotFoundInColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferencedItemTypeName attribute not found for parameter {0} in right {1}..
        /// </summary>
        internal static string ReferencedItemTypeAttributeNotFoundInRightParameter {
            get {
                return ResourceManager.GetString("ReferencedItemTypeAttributeNotFoundInRightParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferencedItemTypeName attribute not found for parameter {0} in view {1}..
        /// </summary>
        internal static string ReferencedItemTypeAttributeNotFoundInViewParameter {
            get {
                return ResourceManager.GetString("ReferencedItemTypeAttributeNotFoundInViewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} on item type {1} references an item type {2} that does not exist..
        /// </summary>
        internal static string ReferencedItemTypeNotFoundForProperty {
            get {
                return ResourceManager.GetString("ReferencedItemTypeNotFoundForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} in view {1} references an ItemType {2} that does not exist..
        /// </summary>
        internal static string ReferencedItemTypeNotFoundInColumn {
            get {
                return ResourceManager.GetString("ReferencedItemTypeNotFoundInColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} in right {1} references an ItemType {2} that does not exist..
        /// </summary>
        internal static string ReferencedItemTypeNotFoundInRightParameter {
            get {
                return ResourceManager.GetString("ReferencedItemTypeNotFoundInRightParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} in view {1} references an ItemType {2} that does not exist..
        /// </summary>
        internal static string ReferencedItemTypeNotFoundInViewParameter {
            get {
                return ResourceManager.GetString("ReferencedItemTypeNotFoundInViewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;StoreSchema&apos; root element not found..
        /// </summary>
        internal static string RootElementNotFound {
            get {
                return ResourceManager.GetString("RootElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute script on a database that has not been initialized.
        /// </summary>
        internal static string SqlInitCantUpgradeEmptyDatabase {
            get {
                return ResourceManager.GetString("SqlInitCantUpgradeEmptyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute script on master database, USE a database before running this script.
        /// </summary>
        internal static string SqlInitCantUseMaster {
            get {
                return ResourceManager.GetString("SqlInitCantUseMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create function for the add security on the {0} item type.
        /// </summary>
        internal static string SqlInitCreateAddItemSecurityFunction {
            get {
                return ResourceManager.GetString("SqlInitCreateAddItemSecurityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create configuration table.
        /// </summary>
        internal static string SqlInitCreateConfigurationTable {
            get {
                return ResourceManager.GetString("SqlInitCreateConfigurationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create function that implements the default view for the {0} item type.
        /// </summary>
        internal static string SqlInitCreateDefaultViewFunction {
            get {
                return ResourceManager.GetString("SqlInitCreateDefaultViewFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create function for the default view security on the {0} item type.
        /// </summary>
        internal static string SqlInitCreateDefaultViewSecurityFunction {
            get {
                return ResourceManager.GetString("SqlInitCreateDefaultViewSecurityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create function for the delete security on the {0} item type.
        /// </summary>
        internal static string SqlInitCreateDeleteItemSecurityFunction {
            get {
                return ResourceManager.GetString("SqlInitCreateDeleteItemSecurityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create function for the security on the {0} right.
        /// </summary>
        internal static string SqlInitCreateRightSecurityFunction {
            get {
                return ResourceManager.GetString("SqlInitCreateRightSecurityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role that can access the database using LearningStore.
        /// </summary>
        internal static string SqlInitCreateRole {
            get {
                return ResourceManager.GetString("SqlInitCreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} table.
        /// </summary>
        internal static string SqlInitCreateTable {
            get {
                return ResourceManager.GetString("SqlInitCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create function for the update security on the {0} item type.
        /// </summary>
        internal static string SqlInitCreateUpdateItemSecurityFunction {
            get {
                return ResourceManager.GetString("SqlInitCreateUpdateItemSecurityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a function that implements the {0} view.
        /// </summary>
        internal static string SqlInitCreateViewFunction {
            get {
                return ResourceManager.GetString("SqlInitCreateViewFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create function for the security on the {0} view.
        /// </summary>
        internal static string SqlInitCreateViewSecurityFunction {
            get {
                return ResourceManager.GetString("SqlInitCreateViewSecurityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop all view/right/security-related functions.
        /// </summary>
        internal static string SqlInitDropFunctions {
            get {
                return ResourceManager.GetString("SqlInitDropFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------------------------------------------------
        ///-- &lt;auto-generated&gt;
        ///-- This code was generated by a tool.
        ///--
        ///-- Changes to this file may cause incorrect behavior and will be lost if
        ///-- the code is regenerated.
        ///-- &lt;/auto-generated&gt;
        ///--------------------------------------------------------------------------------
        ///    .
        /// </summary>
        internal static string SqlInitHeader {
            get {
                return ResourceManager.GetString("SqlInitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update schema XML.
        /// </summary>
        internal static string SqlInitUpdateSchemaXml {
            get {
                return ResourceManager.GetString("SqlInitUpdateSchemaXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} not found.
        /// </summary>
        internal static string TypeStringNotFound {
            get {
                return ResourceManager.GetString("TypeStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected CascadeDelete attribute found for property {0} on item type {1}..
        /// </summary>
        internal static string UnexpectedCascadeDeleteAttributeForProperty {
            get {
                return ResourceManager.GetString("UnexpectedCascadeDeleteAttributeForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected EnumName attribute found for property {0} on item type {1}..
        /// </summary>
        internal static string UnexpectedEnumAttributeForProperty {
            get {
                return ResourceManager.GetString("UnexpectedEnumAttributeForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected EnumName attribute found for column {0} in view {1}..
        /// </summary>
        internal static string UnexpectedEnumAttributeInColumn {
            get {
                return ResourceManager.GetString("UnexpectedEnumAttributeInColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected EnumName attribute found for parameter {0} in right {1}..
        /// </summary>
        internal static string UnexpectedEnumAttributeInRightParameter {
            get {
                return ResourceManager.GetString("UnexpectedEnumAttributeInRightParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected EnumName attribute found for parameter {0} in view {1}..
        /// </summary>
        internal static string UnexpectedEnumAttributeInViewParameter {
            get {
                return ResourceManager.GetString("UnexpectedEnumAttributeInViewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Length attribute found for property {0} on item type {1}..
        /// </summary>
        internal static string UnexpectedLengthAttributeForProperty {
            get {
                return ResourceManager.GetString("UnexpectedLengthAttributeForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected ReferencedItemTypeName attribute found for property {0} on item type {1}..
        /// </summary>
        internal static string UnexpectedReferencedItemTypeAttributeForProperty {
            get {
                return ResourceManager.GetString("UnexpectedReferencedItemTypeAttributeForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected ReferencedItemTypeName attribute found for column {0} in view {1}..
        /// </summary>
        internal static string UnexpectedReferencedItemTypeAttributeInColumn {
            get {
                return ResourceManager.GetString("UnexpectedReferencedItemTypeAttributeInColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected ReferencedItemTypeName attribute found for parameter {0} in right {1}..
        /// </summary>
        internal static string UnexpectedReferencedItemTypeAttributeInRightParameter {
            get {
                return ResourceManager.GetString("UnexpectedReferencedItemTypeAttributeInRightParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected ReferencedItemTypeName attribute found for parameter {0} in view {1}..
        /// </summary>
        internal static string UnexpectedReferencedItemTypeAttributeInViewParameter {
            get {
                return ResourceManager.GetString("UnexpectedReferencedItemTypeAttributeInViewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Usage: SchemaCompiler input-file [/OutputInit init-file]
        ///    [/OutputUpgrade upgrade-file]
        ///    [/OutputHelper helper-file /Namespace namespace /SchemaNamespace namespace]
        ///
        ///SchemaCompiler compiles a schema input file and outputs files that can be used
        ///to install and/or write code using that schema.
        ///
        ///Options include:
        ///  /OutputInit init-file
        ///     This option will output a .sql file that can be used to install the schema
        ///     into a database.
        ///  /OutputUpgrade upgrade-file
        ///     This option will out [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at line {0}, column {1}: {2}.
        /// </summary>
        internal static string XmlSchemaException {
            get {
                return ResourceManager.GetString("XmlSchemaException", resourceCulture);
            }
        }
    }
}
