//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axelerate.SlkCourseManagerLogicalLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axelerate.SlkCourseManagerLogicalLayer.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string strActivity {
            get {
                return ResourceManager.GetString("strActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Group.
        /// </summary>
        internal static string strActivityGroup {
            get {
                return ResourceManager.GetString("strActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        internal static string strAddActivity {
            get {
                return ResourceManager.GetString("strAddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add activity group.
        /// </summary>
        internal static string strAddNewActivityGroup {
            get {
                return ResourceManager.GetString("strAddNewActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string strAssign {
            get {
                return ResourceManager.GetString("strAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Date.
        /// </summary>
        internal static string strAssignDate {
            get {
                return ResourceManager.GetString("strAssignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected row?.
        /// </summary>
        internal static string strConfirmDelete {
            get {
                return ResourceManager.GetString("strConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Total.
        /// </summary>
        internal static string strCourseTotal {
            get {
                return ResourceManager.GetString("strCourseTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string strDelete {
            get {
                return ResourceManager.GetString("strDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Activity.
        /// </summary>
        internal static string strDeleteActivity {
            get {
                return ResourceManager.GetString("strDeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string strDescription {
            get {
                return ResourceManager.GetString("strDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string strDocument {
            get {
                return ResourceManager.GetString("strDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string strDueDate {
            get {
                return ResourceManager.GetString("strDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Week.
        /// </summary>
        internal static string strEndWeek {
            get {
                return ResourceManager.GetString("strEndWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradable.
        /// </summary>
        internal static string strGradable {
            get {
                return ResourceManager.GetString("strGradable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string strGrade {
            get {
                return ResourceManager.GetString("strGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Score.
        /// </summary>
        internal static string strMaxScore {
            get {
                return ResourceManager.GetString("strMaxScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcomes.
        /// </summary>
        internal static string strOutcomes {
            get {
                return ResourceManager.GetString("strOutcomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string strPoints {
            get {
                return ResourceManager.GetString("strPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnToLearner:You must select an assignment column before clicking: Return to Learners.
        /// </summary>
        internal static string strReturnToLearnerError {
            get {
                return ResourceManager.GetString("strReturnToLearnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Learners.
        /// </summary>
        internal static string strReturnToLearners {
            get {
                return ResourceManager.GetString("strReturnToLearners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return all graded assignments to students for the selected task.
        /// </summary>
        internal static string strReturnToLearnersDesc {
            get {
                return ResourceManager.GetString("strReturnToLearnersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Grades.
        /// </summary>
        internal static string strSaveGrades {
            get {
                return ResourceManager.GetString("strSaveGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLK Activities.
        /// </summary>
        internal static string strSlkActivities {
            get {
                return ResourceManager.GetString("strSlkActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your reference, this section displays activities created using the SLK. They are read-only..
        /// </summary>
        internal static string strSlkReadOnlyActivities {
            get {
                return ResourceManager.GetString("strSlkReadOnlyActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string strStartDate {
            get {
                return ResourceManager.GetString("strStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new activity.
        /// </summary>
        internal static string strStartNewActivity {
            get {
                return ResourceManager.GetString("strStartNewActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new activity group.
        /// </summary>
        internal static string strStartNewActivityGroup {
            get {
                return ResourceManager.GetString("strStartNewActivityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Week.
        /// </summary>
        internal static string strStartWeek {
            get {
                return ResourceManager.GetString("strStartWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string strTitle {
            get {
                return ResourceManager.GetString("strTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign.
        /// </summary>
        internal static string strUnassign {
            get {
                return ResourceManager.GetString("strUnassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        internal static string strUnassigned {
            get {
                return ResourceManager.GetString("strUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string strWeight {
            get {
                return ResourceManager.GetString("strWeight", resourceCulture);
            }
        }
    }
}
