//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.LearningComponents.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PackageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.LearningComponents.Storage.Properties.PackageResources", typeof(PackageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; must exist prior to calling this method..
        /// </summary>
        internal static string FSPS_BasePathDirNotFound {
            get {
                return ResourceManager.GetString("FSPS_BasePathDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a unique directory name to use for the files..
        /// </summary>
        internal static string FSPS_CouldNotFindDirectory {
            get {
                return ResourceManager.GetString("FSPS_CouldNotFindDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LearningStoreItemIdentifier {0} does not represent a package in LearningStore..
        /// </summary>
        internal static string FSPS_InvalidPackageId {
            get {
                return ResourceManager.GetString("FSPS_InvalidPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package cannot be added to LearningStore because the manifest in the package cannot be read..
        /// </summary>
        internal static string PS_InvalidManifest {
            get {
                return ResourceManager.GetString("PS_InvalidManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package must contain at least one organization and one item in order to be added to LearningStore..
        /// </summary>
        internal static string PS_NoOrganization {
            get {
                return ResourceManager.GetString("PS_NoOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package cannot be added to the store because it contains at least one error..
        /// </summary>
        internal static string PS_ValidationFailed {
            get {
                return ResourceManager.GetString("PS_ValidationFailed", resourceCulture);
            }
        }
    }
}
