//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteBuilder {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class SiteBuilder : global::System.Configuration.ApplicationSettingsBase {
        
        private static SiteBuilder defaultInstance = ((SiteBuilder)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SiteBuilder())));
        
        public static SiteBuilder Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClassServerDBConnectionString {
            get {
                return ((string)(this["ClassServerDBConnectionString"]));
            }
            set {
                this["ClassServerDBConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveDirectoryPath {
            get {
                return ((string)(this["ActiveDirectoryPath"]));
            }
            set {
                this["ActiveDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClassServerDBServerName {
            get {
                return ((string)(this["ClassServerDBServerName"]));
            }
            set {
                this["ClassServerDBServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClassServerDBUserName {
            get {
                return ((string)(this["ClassServerDBUserName"]));
            }
            set {
                this["ClassServerDBUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClassServerDBPassword {
            get {
                return ((string)(this["ClassServerDBPassword"]));
            }
            set {
                this["ClassServerDBPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClassServerDBName {
            get {
                return ((string)(this["ClassServerDBName"]));
            }
            set {
                this["ClassServerDBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADCheck.log")]
        public string ADCheckLogFile {
            get {
                return ((string)(this["ADCheckLogFile"]));
            }
            set {
                this["ADCheckLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://")]
        public string SLKSchoolWeb {
            get {
                return ((string)(this["SLKSchoolWeb"]));
            }
            set {
                this["SLKSchoolWeb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classes.xml")]
        public string ClassStructureXML {
            get {
                return ((string)(this["ClassStructureXML"]));
            }
            set {
                this["ClassStructureXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SLKSiteCreate.log")]
        public string SLKSiteLogFile {
            get {
                return ((string)(this["SLKSiteLogFile"]));
            }
            set {
                this["SLKSiteLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SLKDocLibraryName {
            get {
                return ((string)(this["SLKDocLibraryName"]));
            }
            set {
                this["SLKDocLibraryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserDataTransfer.log")]
        public string UserDataTransferLogFile {
            get {
                return ((string)(this["UserDataTransferLogFile"]));
            }
            set {
                this["UserDataTransferLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SharePointLearningKit\r\n")]
        public string SLKWebFeatureName {
            get {
                return ((string)(this["SLKWebFeatureName"]));
            }
            set {
                this["SLKWebFeatureName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SLK Instructor")]
        public string SLKInstructorSharePointRole {
            get {
                return ((string)(this["SLKInstructorSharePointRole"]));
            }
            set {
                this["SLKInstructorSharePointRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SLK Learner")]
        public string SLKLearnerSharePointRole {
            get {
                return ((string)(this["SLKLearnerSharePointRole"]));
            }
            set {
                this["SLKLearnerSharePointRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contribute")]
        public string ContributeSharePointRole {
            get {
                return ((string)(this["ContributeSharePointRole"]));
            }
            set {
                this["ContributeSharePointRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Read")]
        public string ReadSharePointRole {
            get {
                return ((string)(this["ReadSharePointRole"]));
            }
            set {
                this["ReadSharePointRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SLKDocLibraryWeb {
            get {
                return ((string)(this["SLKDocLibraryWeb"]));
            }
            set {
                this["SLKDocLibraryWeb"] = value;
            }
        }
    }
}
