//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiteBuilder.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating feature &quot;{0}&quot; on Web site &quot;{1}&quot;.
        /// </summary>
        internal static string ActivatingFeature {
            get {
                return ResourceManager.GetString("ActivatingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. .
        /// </summary>
        internal static string AnError {
            get {
                return ResourceManager.GetString("AnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some application settings were not set. Please go to step 1 to set all the necessary parameters..
        /// </summary>
        internal static string AppSettingsNotSet {
            get {
                return ResourceManager.GetString("AppSettingsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any users in instructor role for the {0}. Assignments for this class will not be transferred..
        /// </summary>
        internal static string AssignmentsTransferErrorNoClassInstructors {
            get {
                return ResourceManager.GetString("AssignmentsTransferErrorNoClassInstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: attempting to create group.
        /// </summary>
        internal static string AttemptingToCreateGroup {
            get {
                return ResourceManager.GetString("AttemptingToCreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: attempting to create site.
        /// </summary>
        internal static string AttemptingToCreateSite {
            get {
                return ResourceManager.GetString("AttemptingToCreateSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured when binding: .
        /// </summary>
        internal static string BindingError {
            get {
                return ResourceManager.GetString("BindingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding is successful..
        /// </summary>
        internal static string BindingSuccessful {
            get {
                return ResourceManager.GetString("BindingSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add users to {0} group. .
        /// </summary>
        internal static string CantAddUsersToGroup {
            get {
                return ResourceManager.GetString("CantAddUsersToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add user {0) to {1} group. .
        /// </summary>
        internal static string CantAddUserToGroup {
            get {
                return ResourceManager.GetString("CantAddUserToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add user {0) to {1} site. .
        /// </summary>
        internal static string CantAddUserToSite {
            get {
                return ResourceManager.GetString("CantAddUserToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create group. .
        /// </summary>
        internal static string CantCreateGroup {
            get {
                return ResourceManager.GetString("CantCreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not transfer assignment &quot; {0} &quot; as the learning resource it uses cannot be found in the document library.
        /// </summary>
        internal static string CantTransferAssignmentNoLearningResource {
            get {
                return ResourceManager.GetString("CantTransferAssignmentNoLearningResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not transfer assignment &quot; {0} &quot; as the learning resource it uses cannot be identified.
        /// </summary>
        internal static string CantTransferAssignmentUnknownLearningResource {
            get {
                return ResourceManager.GetString("CantTransferAssignmentUnknownLearningResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class will not be transferred (Transfer attribute set to 0).
        /// </summary>
        internal static string ClassNotForTransfer {
            get {
                return ResourceManager.GetString("ClassNotForTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is successful..
        /// </summary>
        internal static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while exporting data. .
        /// </summary>
        internal static string DataExportError {
            get {
                return ResourceManager.GetString("DataExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the document library. .
        /// </summary>
        internal static string DocLibraryTestError {
            get {
                return ResourceManager.GetString("DocLibraryTestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some errors in user data transfer. .
        /// </summary>
        internal static string ErrorsMovingUserData {
            get {
                return ResourceManager.GetString("ErrorsMovingUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some errors in processing of XML file. .
        /// </summary>
        internal static string ErrorsProcessingXMLFile {
            get {
                return ResourceManager.GetString("ErrorsProcessingXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...exists already.
        /// </summary>
        internal static string ExistsAlready {
            get {
                return ResourceManager.GetString("ExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export data into {0}.
        /// </summary>
        internal static string FailedToExportData {
            get {
                return ResourceManager.GetString("FailedToExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature &quot;{0}&quot; not found.
        /// </summary>
        internal static string FeatureNotFound {
            get {
                return ResourceManager.GetString("FeatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing class {0}..
        /// </summary>
        internal static string FinishedProcessingClass {
            get {
                return ResourceManager.GetString("FinishedProcessingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group created..
        /// </summary>
        internal static string GroupCreated {
            get {
                return ResourceManager.GetString("GroupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group already exists..
        /// </summary>
        internal static string GroupExists {
            get {
                return ResourceManager.GetString("GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group will not be transferred (Transfer attribute set to 0).
        /// </summary>
        internal static string GroupNotForTransfer {
            get {
                return ResourceManager.GetString("GroupNotForTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group will not be transferred (no valid group owner or default user found).
        /// </summary>
        internal static string GroupOwnerOrDefaultUserProblem {
            get {
                return ResourceManager.GetString("GroupOwnerOrDefaultUserProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group user {0} will not be transferred. (Transfer attribute set to 0) .
        /// </summary>
        internal static string GroupUserNotForTransfer {
            get {
                return ResourceManager.GetString("GroupUserNotForTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is not an instructor for the {1} SLK site..
        /// </summary>
        internal static string InstructorNotRegisteredWithSLKSite {
            get {
                return ResourceManager.GetString("InstructorNotRegisteredWithSLKSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add group owner or default group user. .
        /// </summary>
        internal static string NoGroupOwnerOrDefaultUser {
            get {
                return ResourceManager.GetString("NoGroupOwnerOrDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments for the class {0} will not be transferred (class transfer attribute set to 0)..
        /// </summary>
        internal static string NotTransferringAssignmentsClassNotForTransfer {
            get {
                return ResourceManager.GetString("NotTransferringAssignmentsClassNotForTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing class .
        /// </summary>
        internal static string ProcessingClass {
            get {
                return ResourceManager.GetString("ProcessingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing group {0}.
        /// </summary>
        internal static string ProcessingGroup {
            get {
                return ResourceManager.GetString("ProcessingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composing the learning packages list.
        /// </summary>
        internal static string ReadingPackages {
            get {
                return ResourceManager.GetString("ReadingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  See {0} for more details..
        /// </summary>
        internal static string SeeLogFileForMoreDetails {
            get {
                return ResourceManager.GetString("SeeLogFileForMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site created..
        /// </summary>
        internal static string SiteCreated {
            get {
                return ResourceManager.GetString("SiteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site already exists..
        /// </summary>
        internal static string SiteExists {
            get {
                return ResourceManager.GetString("SiteExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported data into {0}.
        /// </summary>
        internal static string SuccessExportingData {
            get {
                return ResourceManager.GetString("SuccessExportingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished transferring Class Server Assignment Id {0}. New SLK Assignment Id: {1}..
        /// </summary>
        internal static string TransferredAssignment {
            get {
                return ResourceManager.GetString("TransferredAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring assignment id {0} ....
        /// </summary>
        internal static string TransferringAssignment {
            get {
                return ResourceManager.GetString("TransferringAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring assignments for class {0}..
        /// </summary>
        internal static string TransferringAssignmentsForClass {
            get {
                return ResourceManager.GetString("TransferringAssignmentsForClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} added to the {1} group.
        /// </summary>
        internal static string UserAddedToGroup {
            get {
                return ResourceManager.GetString("UserAddedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} added to the {1} site.
        /// </summary>
        internal static string UserAddedToSite {
            get {
                return ResourceManager.GetString("UserAddedToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data transfer is completed successfully. .
        /// </summary>
        internal static string UserDataTransferSuccessful {
            get {
                return ResourceManager.GetString("UserDataTransferSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class user {0} will not be transferred. (Transfer attribute set to 0) .
        /// </summary>
        internal static string UserNotForTransfer {
            get {
                return ResourceManager.GetString("UserNotForTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is not a member of the site {1} as per {2}. Assignment ID {3} can not be assigned to the user..
        /// </summary>
        internal static string UserNotFoundInXMLFile {
            get {
                return ResourceManager.GetString("UserNotFoundInXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is not a member of the {1} SLK site. Assignment ID {2} can not be assigned to the user..
        /// </summary>
        internal static string UserNotRegisteredWithSLKSite {
            get {
                return ResourceManager.GetString("UserNotRegisteredWithSLKSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} users were not found in Active Directory..
        /// </summary>
        internal static string UsersNotFoundInAD {
            get {
                return ResourceManager.GetString("UsersNotFoundInAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the web site. .
        /// </summary>
        internal static string WebConnectionError {
            get {
                return ResourceManager.GetString("WebConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is successful..
        /// </summary>
        internal static string WebConnectionSuccessful {
            get {
                return ResourceManager.GetString("WebConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file processing is completed successfully..
        /// </summary>
        internal static string XMLFileProcessingSuccessful {
            get {
                return ResourceManager.GetString("XMLFileProcessingSuccessful", resourceCulture);
            }
        }
    }
}
