//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axelerate.BusinessLogic.SharedBusinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axelerate.BusinessLogic.SharedBusinessLogic.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Execution &lt;-------.
        /// </summary>
        internal static string afterExecution {
            get {
                return ResourceManager.GetString("afterExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Execution &lt;-------.
        /// </summary>
        internal static string beforeExecution {
            get {
                return ResourceManager.GetString("beforeExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , but the user owner of this Object is:.
        /// </summary>
        internal static string butOwnerOfObject {
            get {
                return ResourceManager.GetString("butOwnerOfObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clsDirectory -- EnumarateDomains() -.
        /// </summary>
        internal static string clsDirectoryEnumerateDomains {
            get {
                return ResourceManager.GetString("clsDirectoryEnumerateDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to acquire connection.
        /// </summary>
        internal static string errAquireConnection {
            get {
                return ResourceManager.GetString("errAquireConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create the following Dictionaries:.
        /// </summary>
        internal static string errCantCreateDict {
            get {
                return ResourceManager.GetString("errCantCreateDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create the following types:.
        /// </summary>
        internal static string errCantCreateTypes {
            get {
                return ResourceManager.GetString("errCantCreateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command is in an invalid State.
        /// </summary>
        internal static string errCommandInvalidState {
            get {
                return ResourceManager.GetString("errCommandInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection info has been specified.
        /// </summary>
        internal static string errConInfo {
            get {
                return ResourceManager.GetString("errConInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on the connection:.
        /// </summary>
        internal static string errConnection {
            get {
                return ResourceManager.GetString("errConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred..
        /// </summary>
        internal static string errException {
            get {
                return ResourceManager.GetString("errException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while accessing GetDirectoryObject().
        /// </summary>
        internal static string errGetDirectoryObject {
            get {
                return ResourceManager.GetString("errGetDirectoryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection type.
        /// </summary>
        internal static string errInvalidConType {
            get {
                return ResourceManager.GetString("errInvalidConType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogonUser call failed with error code :.
        /// </summary>
        internal static string errLogonFailed {
            get {
                return ResourceManager.GetString("errLogonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object was not found.
        /// </summary>
        internal static string errObjectNotFound {
            get {
                return ResourceManager.GetString("errObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while preparing to send an email:.
        /// </summary>
        internal static string errPreparingEmail {
            get {
                return ResourceManager.GetString("errPreparingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while sending an email:.
        /// </summary>
        internal static string errSendingEmail {
            get {
                return ResourceManager.GetString("errSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , isn&apos;t locked, but this Object should be Locked..
        /// </summary>
        internal static string errShouldBeLocked {
            get {
                return ResourceManager.GetString("errShouldBeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , is locked, but this Object should be UnLocked..
        /// </summary>
        internal static string errShouldBeUnlocked {
            get {
                return ResourceManager.GetString("errShouldBeUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDirectoryObject -- exception=.
        /// </summary>
        internal static string excGetDirectoryObject {
            get {
                return ResourceManager.GetString("excGetDirectoryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Objects:.
        /// </summary>
        internal static string freeObjects {
            get {
                return ResourceManager.GetString("freeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isn&apos;t Locked..
        /// </summary>
        internal static string isNotLocked {
            get {
                return ResourceManager.GetString("isNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Persistent Lock with Object GUID:.
        /// </summary>
        internal static string lockWithObjectGUID {
            get {
                return ResourceManager.GetString("lockWithObjectGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Object with GUID:.
        /// </summary>
        internal static string theObjectWithGUID {
            get {
                return ResourceManager.GetString("theObjectWithGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user.
        /// </summary>
        internal static string theUser {
            get {
                return ResourceManager.GetString("theUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tried to UnLock the Persistent Lock-Object with GUID:.
        /// </summary>
        internal static string triedToUnlockALockObject {
            get {
                return ResourceManager.GetString("triedToUnlockALockObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Objects:.
        /// </summary>
        internal static string usedObjects {
            get {
                return ResourceManager.GetString("usedObjects", resourceCulture);
            }
        }
    }
}
