//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axelerate.BusinessLayerUITools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axelerate.BusinessLayerUITools.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object doesn&apos;t accept the AllowedValues attribute..
        /// </summary>
        internal static string errAllowedValuesAttibute {
            get {
                return ResourceManager.GetString("errAllowedValuesAttibute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the key &apos;WebApplicationPath&apos;.
        /// </summary>
        internal static string errCantFindWebApplicationPath {
            get {
                return ResourceManager.GetString("errCantFindWebApplicationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data must support IBLMNRelationBusinessBase or BLBusinessBase.
        /// </summary>
        internal static string errDataSupportIBLMNR {
            get {
                return ResourceManager.GetString("errDataSupportIBLMNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row can&apos;t be deleted becase a internal error occur.
        /// </summary>
        internal static string errDeletingARowOnGrid {
            get {
                return ResourceManager.GetString("errDeletingARowOnGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to evaluate {0}.
        /// </summary>
        internal static string errEval0 {
            get {
                return ResourceManager.GetString("errEval0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid child tag name.
        /// </summary>
        internal static string errInvalidChildTagName {
            get {
                return ResourceManager.GetString("errInvalidChildTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ClassName.
        /// </summary>
        internal static string errInvalidClassName {
            get {
                return ResourceManager.GetString("errInvalidClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        internal static string errInvalidDatasource {
            get {
                return ResourceManager.GetString("errInvalidDatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Factory Method.
        /// </summary>
        internal static string errInvalidFactoryMethod {
            get {
                return ResourceManager.GetString("errInvalidFactoryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Factory Parameters.
        /// </summary>
        internal static string errInvalidFactoryParameters {
            get {
                return ResourceManager.GetString("errInvalidFactoryParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Fieldname.
        /// </summary>
        internal static string errInvalidFieldName {
            get {
                return ResourceManager.GetString("errInvalidFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Name not Found.
        /// </summary>
        internal static string errInvalidLayoutName {
            get {
                return ResourceManager.GetString("errInvalidLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Literal String.
        /// </summary>
        internal static string errInvalidLiteralString {
            get {
                return ResourceManager.GetString("errInvalidLiteralString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TreeView Object associated to the node..
        /// </summary>
        internal static string errInvalidTreeViewObject {
            get {
                return ResourceManager.GetString("errInvalidTreeViewObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Type..
        /// </summary>
        internal static string errInvalidType {
            get {
                return ResourceManager.GetString("errInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string errMethodNotImplemented {
            get {
                return ResourceManager.GetString("errMethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to view this information.
        /// </summary>
        internal static string errMissingPermissions {
            get {
                return ResourceManager.GetString("errMissingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the Tree Items does not has the \&apos;{0}\&apos; property..
        /// </summary>
        internal static string errNotHasProperty {
            get {
                return ResourceManager.GetString("errNotHasProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to display.
        /// </summary>
        internal static string errNothingToDisplay {
            get {
                return ResourceManager.GetString("errNothingToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not found..
        /// </summary>
        internal static string errObjectNotFound {
            get {
                return ResourceManager.GetString("errObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to get the Object Properties..
        /// </summary>
        internal static string errObjectProp {
            get {
                return ResourceManager.GetString("errObjectProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permissions to access this property..
        /// </summary>
        internal static string errPermissionsAccessProperty {
            get {
                return ResourceManager.GetString("errPermissionsAccessProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property not found:.
        /// </summary>
        internal static string errPropNotFound {
            get {
                return ResourceManager.GetString("errPropNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        internal static string errRequiredValue {
            get {
                return ResourceManager.GetString("errRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes can be saved because the new element is not in a valid state..
        /// </summary>
        internal static string errSavingBOInvalidState {
            get {
                return ResourceManager.GetString("errSavingBOInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag \&quot;ID\&quot; missing in control:.
        /// </summary>
        internal static string errTagIDMissingInControl {
            get {
                return ResourceManager.GetString("errTagIDMissingInControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index format {0}.
        /// </summary>
        internal static string errTreeInvalidIndexFormat {
            get {
                return ResourceManager.GetString("errTreeInvalidIndexFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected node {0} is a non visible node..
        /// </summary>
        internal static string errTreeInvisibleSelectedNode {
            get {
                return ResourceManager.GetString("errTreeInvisibleSelectedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The treenode is already in a collection.
        /// </summary>
        internal static string errTreeNodeAlreadyInCollection {
            get {
                return ResourceManager.GetString("errTreeNodeAlreadyInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add row: The field {0} has an invalid value ({1})..
        /// </summary>
        internal static string errTryingConvertValueOnAddrow {
            get {
                return ResourceManager.GetString("errTryingConvertValueOnAddrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes: The field {0} has an invalid value ({1})..
        /// </summary>
        internal static string errTryingConvertValueOnSaveChanges {
            get {
                return ResourceManager.GetString("errTryingConvertValueOnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Parameter Found.
        /// </summary>
        internal static string wrnNullParameter {
            get {
                return ResourceManager.GetString("wrnNullParameter", resourceCulture);
            }
        }
    }
}
