//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axelerate.BusinessLayerUITools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GenericWebParts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericWebParts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axelerate.BusinessLayerUITools.Resources.GenericWebParts", typeof(GenericWebParts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Done..
        /// </summary>
        internal static string strBussinesMethodCalledSuccessfull {
            get {
                return ResourceManager.GetString("strBussinesMethodCalledSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control type {0} is not supported by this webpart..
        /// </summary>
        internal static string strErrorControlTypeNotSupported {
            get {
                return ResourceManager.GetString("strErrorControlTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load dynamic columns..
        /// </summary>
        internal static string strErrorNullRepeatable {
            get {
                return ResourceManager.GetString("strErrorNullRepeatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error parsing the parameters..
        /// </summary>
        internal static string strErrorParsingParameters {
            get {
                return ResourceManager.GetString("strErrorParsingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Object type {0} has no definition of {1}.
        /// </summary>
        internal static string strErrorPropertyNotFound {
            get {
                return ResourceManager.GetString("strErrorPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;PropertyName&quot; attribute was not found in the {0} tag.
        /// </summary>
        internal static string strErrorPropertyNotFoundInLayout {
            get {
                return ResourceManager.GetString("strErrorPropertyNotFoundInLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} does not inherit from IBLListBase.
        /// </summary>
        internal static string strErrorPropertyType {
            get {
                return ResourceManager.GetString("strErrorPropertyType", resourceCulture);
            }
        }
    }
}
