//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slkadm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("slkadm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///           slkadm.exe -o &lt;operation&gt; [&lt;parameters&gt;]
        ///           slkadm.exe -help &lt;operation&gt;
        ///
        ///Operations:
        ///           configuresite
        ///           getsiteconfiguration
        ///           enummappings
        ///           deletemapping
        ///
        ///Examples:
        ///slkadm.exe -o configuresite
        ///           -url http://server/site
        ///           -databaseserver mydbserver
        ///           -databasename slkdb
        ///           -createdatabase
        ///slkadm.exe -o getsiteconfiguration
        ///           -url http://server/site
        ///slkadm.exe -o enummappings
        ///slkadm.e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppUsage {
            get {
                return ResourceManager.GetString("AppUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Command line error.
        ///.
        /// </summary>
        internal static string CommandLineError {
            get {
                return ResourceManager.GetString("CommandLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///slkadm.exe -o configuresite
        ///           -url &lt;url&gt;
        ///           [-databaseserver &lt;database server name*&gt;]
        ///           [-databasename &lt;database name&gt;]
        ///           [-createdatabase]
        ///           [-instructorpermission &lt;instructor permission name&gt;]
        ///           [-learnerpermission &lt;learner permission name&gt;]
        ///           [-createpermissions]
        ///           [-uploadslksettings &lt;SLK Settings XML file name&gt; | -defaultslksettings]
        ///
        ///* By default, integrated authentication is used to connect to the database.
        ///To use a S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigureSiteHelp {
            get {
                return ResourceManager.GetString("ConfigureSiteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring SLK for site: {0} ({1}).
        /// </summary>
        internal static string ConfiguringSlk {
            get {
                return ResourceManager.GetString("ConfiguringSlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///slkadm.exe -o deletemapping
        ///           -guid &lt;site-guid&gt;
        ///.
        /// </summary>
        internal static string DeleteMappingHelp {
            get {
                return ResourceManager.GetString("DeleteMappingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///slkadm.exe -o enummappings
        ///.
        /// </summary>
        internal static string EnumMappingsHelp {
            get {
                return ResourceManager.GetString("EnumMappingsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///slkadm.exe -o getsiteconfiguration
        ///           -url &lt;url&gt;
        ///.
        /// </summary>
        internal static string GetSiteConfigurationHelp {
            get {
                return ResourceManager.GetString("GetSiteConfigurationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLK mapping deleted for SPSite GUID {0}.
        /// </summary>
        internal static string MappingDeleted {
            get {
                return ResourceManager.GetString("MappingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLK mapping not found for SPSite GUID {0}.
        /// </summary>
        internal static string MappingNotFound {
            get {
                return ResourceManager.GetString("MappingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key....
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SLK configuration found for {0} ({1}); default settings are:.
        /// </summary>
        internal static string SiteConfig_ConfigNotFound {
            get {
                return ResourceManager.GetString("SiteConfig_ConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Database needs to be created: {0}.
        /// </summary>
        internal static string SiteConfig_CreateDatabase {
            get {
                return ResourceManager.GetString("SiteConfig_CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Permissions need to be created: {0}.
        /// </summary>
        internal static string SiteConfig_CreatePermissions {
            get {
                return ResourceManager.GetString("SiteConfig_CreatePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Database name: {0}.
        /// </summary>
        internal static string SiteConfig_DatabaseName {
            get {
                return ResourceManager.GetString("SiteConfig_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Database server: {0}.
        /// </summary>
        internal static string SiteConfig_DatabaseServer {
            get {
                return ResourceManager.GetString("SiteConfig_DatabaseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found SLK configuration for {0} ({1}):.
        /// </summary>
        internal static string SiteConfig_FoundConfig {
            get {
                return ResourceManager.GetString("SiteConfig_FoundConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Instructor permission: {0}.
        /// </summary>
        internal static string SiteConfig_InstructorPermission {
            get {
                return ResourceManager.GetString("SiteConfig_InstructorPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Learner permission: {0}.
        /// </summary>
        internal static string SiteConfig_LearnerPermission {
            get {
                return ResourceManager.GetString("SiteConfig_LearnerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;site not found&gt;.
        /// </summary>
        internal static string SiteNotFoundLabel {
            get {
                return ResourceManager.GetString("SiteNotFoundLabel", resourceCulture);
            }
        }
    }
}
