//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.LearningComponents.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LearningStoreStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LearningStoreStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.LearningComponents.Storage.LearningStoreStrings", typeof(LearningStoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one output column must be specified in the query..
        /// </summary>
        internal static string AtLeastOneOutputColumnMustBeSpecified {
            get {
                return ResourceManager.GetString("AtLeastOneOutputColumnMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one value must be provided..
        /// </summary>
        internal static string AtLeastOneValueMustBeProvided {
            get {
                return ResourceManager.GetString("AtLeastOneValueMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;Id&apos; can not be changed..
        /// </summary>
        internal static string CannotChangeIdProperty {
            get {
                return ResourceManager.GetString("CannotChangeIdProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; has already been added to the query.
        /// </summary>
        internal static string ColumnAlreadyExistsInQuery {
            get {
                return ResourceManager.GetString("ColumnAlreadyExistsInQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sort order for the specified column already exists in the query..
        /// </summary>
        internal static string ColumnAlreadySortedOn {
            get {
                return ResourceManager.GetString("ColumnAlreadySortedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column can not be sorted on..
        /// </summary>
        internal static string ColumnCannotBeSorted {
            get {
                return ResourceManager.GetString("ColumnCannotBeSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; not found in the view..
        /// </summary>
        internal static string ColumnNotFound {
            get {
                return ResourceManager.GetString("ColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method has already been called..
        /// </summary>
        internal static string CompleteAlreadyCalled {
            get {
                return ResourceManager.GetString("CompleteAlreadyCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug log has already been enabled..
        /// </summary>
        internal static string DebugLogAlreadyEnabled {
            get {
                return ResourceManager.GetString("DebugLogAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one value has been provided for property &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicatePropertyValue {
            get {
                return ResourceManager.GetString("DuplicatePropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum type &apos;{0}&apos; not found in the schema..
        /// </summary>
        internal static string EnumTypeNotFoundInSchema {
            get {
                return ResourceManager.GetString("EnumTypeNotFoundInSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was created by a different version of this product..
        /// </summary>
        internal static string IncompatibleEngineVersion {
            get {
                return ResourceManager.GetString("IncompatibleEngineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid condition operator: a Guid column can only be compared with an equality or inequality operator..
        /// </summary>
        internal static string InvalidConditionOperatorForGuidColumn {
            get {
                return ResourceManager.GetString("InvalidConditionOperatorForGuidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid condition value: an Xml column can only be compared against null..
        /// </summary>
        internal static string InvalidConditionValueForXmlColumn {
            get {
                return ResourceManager.GetString("InvalidConditionValueForXmlColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid condition value: {0}.
        /// </summary>
        internal static string InvalidConditionValueWithDescription {
            get {
                return ResourceManager.GetString("InvalidConditionValueWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid condition value: only item identifiers with unique keys can be compared against..
        /// </summary>
        internal static string InvalidIdConditionValue {
            get {
                return ResourceManager.GetString("InvalidIdConditionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter value: only item identifiers with unique keys can be used as parameters..
        /// </summary>
        internal static string InvalidIdParameterValue {
            get {
                return ResourceManager.GetString("InvalidIdParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid condition operator: null can only be compared with an equality or inequality operator..
        /// </summary>
        internal static string InvalidOperatorForNullConditionValue {
            get {
                return ResourceManager.GetString("InvalidOperatorForNullConditionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidParameterValue {
            get {
                return ResourceManager.GetString("InvalidParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter value: {0}.
        /// </summary>
        internal static string InvalidParameterValueWithDescription {
            get {
                return ResourceManager.GetString("InvalidParameterValueWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string InvalidParameterValueWithDescriptionAndName {
            get {
                return ResourceManager.GetString("InvalidParameterValueWithDescriptionAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for property &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidPropertyValue {
            get {
                return ResourceManager.GetString("InvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for property &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string InvalidPropertyValueWithDescription {
            get {
                return ResourceManager.GetString("InvalidPropertyValueWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid schema definition.
        /// </summary>
        internal static string InvalidSchemaDefinition {
            get {
                return ResourceManager.GetString("InvalidSchemaDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid schema definition, Invalid enum..
        /// </summary>
        internal static string InvalidSchemaDefinitionEnum {
            get {
                return ResourceManager.GetString("InvalidSchemaDefinitionEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid schema definition. No ReferencedItemTypeName value..
        /// </summary>
        internal static string InvalidSchemaDefinitionNoReference {
            get {
                return ResourceManager.GetString("InvalidSchemaDefinitionNoReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid schema definition. Invalid type..
        /// </summary>
        internal static string InvalidSchemaDefinitionType {
            get {
                return ResourceManager.GetString("InvalidSchemaDefinitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction scope nesting..
        /// </summary>
        internal static string InvalidScopeNesting {
            get {
                return ResourceManager.GetString("InvalidScopeNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        internal static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item type &apos;{0}&apos; not found in the schema..
        /// </summary>
        internal static string ItemTypeNotFoundInSchema {
            get {
                return ResourceManager.GetString("ItemTypeNotFoundInSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolation level specified for the transaction doesn&apos;t match the isolation level for the currently-existing transaction..
        /// </summary>
        internal static string MismatchedIsolationLevel {
            get {
                return ResourceManager.GetString("MismatchedIsolationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one item matches the properties in the AddOrUpdateItem command..
        /// </summary>
        internal static string MoreThanOneItemFoundInAddOrUpdate {
            get {
                return ResourceManager.GetString("MoreThanOneItemFoundInAddOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object reference not set to an instance of an object when attempting to access database.  Database connection may have been lost..
        /// </summary>
        internal static string NullReferenceWhenAccessingDatabase {
            get {
                return ResourceManager.GetString("NullReferenceWhenAccessingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed because of a constraint violation..
        /// </summary>
        internal static string OperationFailedBecauseOfConstraintViolation {
            get {
                return ResourceManager.GetString("OperationFailedBecauseOfConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; not found in the view..
        /// </summary>
        internal static string ParameterNotFound {
            get {
                return ResourceManager.GetString("ParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; not found in the right..
        /// </summary>
        internal static string ParameterNotFoundInRight {
            get {
                return ResourceManager.GetString("ParameterNotFoundInRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive value expected.
        /// </summary>
        internal static string PositiveValueExpected {
            get {
                return ResourceManager.GetString("PositiveValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; not found.
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for property &apos;{0}&apos; not found.
        /// </summary>
        internal static string PropertyValueNotFound {
            get {
                return ResourceManager.GetString("PropertyValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query is not compatible with this LearningStore instance..
        /// </summary>
        internal static string QueryNotCompatibleWithStore {
            get {
                return ResourceManager.GetString("QueryNotCompatibleWithStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results of the job can not be cast to the specified return value..
        /// </summary>
        internal static string ResultsOfJobCanNotBeCast {
            get {
                return ResourceManager.GetString("ResultsOfJobCanNotBeCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right &apos;{0}&apos; not found in the schema..
        /// </summary>
        internal static string RightNotFoundInSchema {
            get {
                return ResourceManager.GetString("RightNotFoundInSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction scope disposed in invalid thread..
        /// </summary>
        internal static string ScopeDisposedInInvalidThread {
            get {
                return ResourceManager.GetString("ScopeDisposedInInvalidThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security check failed..
        /// </summary>
        internal static string SecurityCheckFailed {
            get {
                return ResourceManager.GetString("SecurityCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout value specified for the transaction must be zero..
        /// </summary>
        internal static string TimeoutMustBeZero {
            get {
                return ResourceManager.GetString("TimeoutMustBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction already exists in this scope..
        /// </summary>
        internal static string TransactionAlreadyExists {
            get {
                return ResourceManager.GetString("TransactionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique key not available..
        /// </summary>
        internal static string UniqueKeyNotAvailable {
            get {
                return ResourceManager.GetString("UniqueKeyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be null..
        /// </summary>
        internal static string ValueCannotBeNull {
            get {
                return ResourceManager.GetString("ValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cast..
        /// </summary>
        internal static string ValueCausesInvalidCast {
            get {
                return ResourceManager.GetString("ValueCausesInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow..
        /// </summary>
        internal static string ValueCausesOverflow {
            get {
                return ResourceManager.GetString("ValueCausesOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format..
        /// </summary>
        internal static string ValueHasInvalidFormat {
            get {
                return ResourceManager.GetString("ValueHasInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a System.Byte array..
        /// </summary>
        internal static string ValueMustBeByteArray {
            get {
                return ResourceManager.GetString("ValueMustBeByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a Guid..
        /// </summary>
        internal static string ValueMustBeGuid {
            get {
                return ResourceManager.GetString("ValueMustBeGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a LearningStoreItemIdentifier with ItemType &apos;{0}&apos;..
        /// </summary>
        internal static string ValueMustBeItemIdentifier {
            get {
                return ResourceManager.GetString("ValueMustBeItemIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid value from &apos;{0}&apos;..
        /// </summary>
        internal static string ValueMustBeValidEnumValue {
            get {
                return ResourceManager.GetString("ValueMustBeValidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between SqlDateTime.MinValue and SqlDateTime.MaxValue..
        /// </summary>
        internal static string ValueMustBeWithinSqlDateTimeRange {
            get {
                return ResourceManager.GetString("ValueMustBeWithinSqlDateTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a LearningStoreXml..
        /// </summary>
        internal static string ValueMustBeXml {
            get {
                return ResourceManager.GetString("ValueMustBeXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View &apos;{0}&apos; not found in the schema..
        /// </summary>
        internal static string ViewNotFoundInSchema {
            get {
                return ResourceManager.GetString("ViewNotFoundInSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot search on XML property &apos;{0}&apos;..
        /// </summary>
        internal static string XmlPropertyCannotBeSearchedOn {
            get {
                return ResourceManager.GetString("XmlPropertyCannotBeSearchedOn", resourceCulture);
            }
        }
    }
}
