//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.LearningComponents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.LearningComponents.Properties.AIResources", typeof(AIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an attached {0} file..
        /// </summary>
        internal static string AttachedFileHtml {
            get {
                return ResourceManager.GetString("AttachedFileHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseHtml {
            get {
                return ResourceManager.GetString("BrowseHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file to attach:.
        /// </summary>
        internal static string ChooseFileToAttachHtml {
            get {
                return ResourceManager.GetString("ChooseFileToAttachHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer:.
        /// </summary>
        internal static string CorrectAnswerColonHtml {
            get {
                return ResourceManager.GetString("CorrectAnswerColonHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        internal static string CorrectAnswerHtml {
            get {
                return ResourceManager.GetString("CorrectAnswerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        internal static string CorrectAnswerSeparatorHtml {
            get {
                return ResourceManager.GetString("CorrectAnswerSeparatorHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach File.
        /// </summary>
        internal static string DetachFileHtml {
            get {
                return ResourceManager.GetString("DetachFileHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A requested file attachment could not be found..
        /// </summary>
        internal static string FileAttachmentNotFound {
            get {
                return ResourceManager.GetString("FileAttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A requested file could not be found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&quot;javascript&quot;&gt;
        ///var ECS_ViewType=2;
        ///
        /// //=============================================================================
        /// //  Handles calls to detach an attached file.  The id of this question will
        /// //  be sent in the hidDetach field.   At the server end, if this value is
        /// //  non-zero, then there is a file to be detached..
        ///
        ///function OnDetach( attachmentId )
        ///{
        ///	// attachmentId is of the form &lt;interactionId&gt;*A*&lt;attachmentOrdinal&gt;
        ///
        ///	var oForm = document.forms[&quot;frmPage&quot;];
        ///	oForm.elemen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HeadExecuteViewScript {
            get {
                return ResourceManager.GetString("HeadExecuteViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&quot;javascript&quot; type=&quot;text/javascript&quot;&gt;
        ///var ECS_ViewType=6;
        ///
        ///function mlc_RoundTwoDecimalPlaces(val)
        ///{
        ///	return (Math.round( val * 100 ) / 100);
        ///}
        ///
        ///function mlc_CultureStringToDouble(score)
        ///{
        ///	var re = new RegExp( &quot;^[\\+\\-]?[0-9]*(\\x&lt;%=DecimalSeparatorHex%&gt;)?[0-9]*$&quot; );
        ///	var check = score.match(re);
        ///	if( check == null ) return NaN;
        ///	else return parseFloat(score.replace( &quot;&lt;%=DecimalSeparator%&gt;&quot;, &quot;.&quot; ));
        ///}
        ///
        ///function mlc_DoubleToCultureString(dbl)
        ///{
        ///	// convert a double into a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HeadGradingViewScript {
            get {
                return ResourceManager.GetString("HeadGradingViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect answer.
        /// </summary>
        internal static string IncorrectAnswerHtml {
            get {
                return ResourceManager.GetString("IncorrectAnswerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor comments:.
        /// </summary>
        internal static string InstructorCommentsColonHtml {
            get {
                return ResourceManager.GetString("InstructorCommentsColonHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The text entered is formatted incorrectly or greater than the maximum {0} characters.&quot;.
        /// </summary>
        internal static string InstructorCommentTooLong {
            get {
                return ResourceManager.GetString("InstructorCommentTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value, {0}, of the form field, {1}, is invalid..
        /// </summary>
        internal static string InvalidFormFieldValue {
            get {
                return ResourceManager.GetString("InvalidFormFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the id is invalid in the assessment markup: {0}.
        /// </summary>
        internal static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The posted &lt;option&gt; value, {0}, is out of range for the &lt;select&gt; tag with name=&quot;{1}&quot;..
        /// </summary>
        internal static string InvalidOptionValue {
            get {
                return ResourceManager.GetString("InvalidOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type attribute has an invalid value in the assessment markup: {0}.
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form field, {0}, is missing..
        /// </summary>
        internal static string MissingFormField {
            get {
                return ResourceManager.GetString("MissingFormField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file attached..
        /// </summary>
        internal static string NoFileAttachedHtml {
            get {
                return ResourceManager.GetString("NoFileAttachedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string NoScoreHtml {
            get {
                return ResourceManager.GetString("NoScoreHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the attached file with another file:.
        /// </summary>
        internal static string ReplaceFileHtml {
            get {
                return ResourceManager.GetString("ReplaceFileHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&quot;javascript&quot;&gt;
        ///var ECS_ViewType=4;
        ///&lt;/script&gt;.
        /// </summary>
        internal static string ReviewViewScript {
            get {
                return ResourceManager.GetString("ReviewViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The score entered is formatted incorrectly or outside the allowable range of -1000 to 1000.&quot;.
        /// </summary>
        internal static string ScoreOutOfRange {
            get {
                return ResourceManager.GetString("ScoreOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        internal static string StudentNotSelectedHtml {
            get {
                return ResourceManager.GetString("StudentNotSelectedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the correct answer but it was not selected.
        /// </summary>
        internal static string StudentNotSelectedIncorrectHtml {
            get {
                return ResourceManager.GetString("StudentNotSelectedIncorrectHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        internal static string StudentSelectedCorrectHtml {
            get {
                return ResourceManager.GetString("StudentSelectedCorrectHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string StudentSelectedHtml {
            get {
                return ResourceManager.GetString("StudentSelectedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect answer.
        /// </summary>
        internal static string StudentSelectedIncorrectHtml {
            get {
                return ResourceManager.GetString("StudentSelectedIncorrectHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unanswered&gt;.
        /// </summary>
        internal static string Unanswered {
            get {
                return ResourceManager.GetString("Unanswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View File.
        /// </summary>
        internal static string ViewFileHtml {
            get {
                return ResourceManager.GetString("ViewFileHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the attached file..
        /// </summary>
        internal static string ViewTheAttachedFileHtml {
            get {
                return ResourceManager.GetString("ViewTheAttachedFileHtml", resourceCulture);
            }
        }
    }
}
