//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.LearningComponents.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SessionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.LearningComponents.Storage.Properties.SessionResources", typeof(SessionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current activity cannot be abandoned. There must be a current activity in an active session in order to abandon it. .
        /// </summary>
        internal static string SLS_AbandonCurrentActivityNotValid {
            get {
                return ResourceManager.GetString("SLS_AbandonCurrentActivityNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session cannot be abandoned in its current state. In Execute view, only Active sessions may be abandoned. Sessions may not be abandoned in other views..
        /// </summary>
        internal static string SLS_AbandonNotValid {
            get {
                return ResourceManager.GetString("SLS_AbandonNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt associated with this session has not ended..
        /// </summary>
        internal static string SLS_AttemptEndTimeNotValid {
            get {
                return ResourceManager.GetString("SLS_AttemptEndTimeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt has already started. You may not call Start more than once..
        /// </summary>
        internal static string SLS_AttemptHasStarted {
            get {
                return ResourceManager.GetString("SLS_AttemptHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes to the current session cannot be committed. The session may not be in Review view when calling this method. .
        /// </summary>
        internal static string SLS_CommitChangesNotValid {
            get {
                return ResourceManager.GetString("SLS_CommitChangesNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An initial activity could not be identified in the session..
        /// </summary>
        internal static string SLS_CouldNotFindFirstActivity {
            get {
                return ResourceManager.GetString("SLS_CouldNotFindFirstActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current activity cannot be exited. There must be a current activity in an active session in order to exit it. .
        /// </summary>
        internal static string SLS_ExitCurrentActivityNotValid {
            get {
                return ResourceManager.GetString("SLS_ExitCurrentActivityNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session cannot be exited in its current state. In Execute view, only Active sessions which have been started may be exited. Sessions may not be exited in other views..
        /// </summary>
        internal static string SLS_ExitNotValid {
            get {
                return ResourceManager.GetString("SLS_ExitNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session cache cannot be cleared because the current session contains an active attempt. .
        /// </summary>
        internal static string SLS_InvalidateSessionCacheNotValid {
            get {
                return ResourceManager.GetString("SLS_InvalidateSessionCacheNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LoggingOptions property may not be set when reviewing a session..
        /// </summary>
        internal static string SLS_LoggingFlagsSetNotValid {
            get {
                return ResourceManager.GetString("SLS_LoggingFlagsSetNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session is not in a state where a new activity may be selected. In Execute view, only Active sessions may navigate to a selected activity..
        /// </summary>
        internal static string SLS_MoveToActivityNotValid {
            get {
                return ResourceManager.GetString("SLS_MoveToActivityNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to the next activity is not valid. In Execute view, only Active sessions with a current activity may navigate to the next activity..
        /// </summary>
        internal static string SLS_MoveToNextNotValid {
            get {
                return ResourceManager.GetString("SLS_MoveToNextNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to the previous activity is not valid. In Execute view, only Active sessions with a current activity may navigate to the next activity..
        /// </summary>
        internal static string SLS_MoveToPreviousNotValid {
            get {
                return ResourceManager.GetString("SLS_MoveToPreviousNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation requests cannot be processed. In an ExecuteView, the AttemptStatus must be Active. This call is not valid in RandomAccess and Review views..
        /// </summary>
        internal static string SLS_ProcessNavigationRequestsNotValid {
            get {
                return ResourceManager.GetString("SLS_ProcessNavigationRequestsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not valid to reactivate the current session. Only a completed or abandoned session may be reactivated, and only in RandomAccess view..
        /// </summary>
        internal static string SLS_ReactivateNotValid {
            get {
                return ResourceManager.GetString("SLS_ReactivateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content cannot be rendered. In Execute view, the session must have an AttemptStatus of Active..
        /// </summary>
        internal static string SLS_RenderNotValid {
            get {
                return ResourceManager.GetString("SLS_RenderNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current activity in the session does not have an associated resource. The content cannot be displayed..
        /// </summary>
        internal static string SLS_ResourceNotFound {
            get {
                return ResourceManager.GetString("SLS_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session cannot be resumed in its current state. In Execute view, only Suspended sessions may be resumed. Sessions may not be resumed in other views..
        /// </summary>
        internal static string SLS_ResumeNotValid {
            get {
                return ResourceManager.GetString("SLS_ResumeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session may only be started on an active attempt in ExecuteView. The session may not be in Review or RandomAccess view when calling this method..
        /// </summary>
        internal static string SLS_StartNotValid {
            get {
                return ResourceManager.GetString("SLS_StartNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session cannot be suspended in its current state. In Execute view, only Active sessions may be suspended. Sessions may not be suspended in other views..
        /// </summary>
        internal static string SLS_SuspendNotValid {
            get {
                return ResourceManager.GetString("SLS_SuspendNotValid", resourceCulture);
            }
        }
    }
}
