
# AxelerateLibraries makefile

all: deb rel

deb:
	devenv CourseManagerConfCs.sln /build Debug 

rel:
	devenv CourseManagerConfCs.sln /build Release 

ide:
	devenv CourseManagerConfCs.sln

clean: 
	devenv CourseManagerConfCs.sln /clean Debug
	devenv CourseManagerConfCs.sln /clean Release

