//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionsAndFeaturesTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InstallerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionsAndFeaturesTest.InstallerResources", typeof(InstallerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating .
        /// </summary>
        internal static string strActivating {
            get {
                return ResourceManager.GetString("strActivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Microsoft .Net Framework .
        /// </summary>
        internal static string strCheckingNetVersion {
            get {
                return ResourceManager.GetString("strCheckingNetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking SharePoint Learning Kit (SLk) Version 1.3.1....
        /// </summary>
        internal static string strCheckingSLKVersion {
            get {
                return ResourceManager.GetString("strCheckingSLKVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying SPDocumentSelectorIFrame.js....
        /// </summary>
        internal static string strCopyingDocumentSelector {
            get {
                return ResourceManager.GetString("strCopyingDocumentSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying .
        /// </summary>
        internal static string strDeploying {
            get {
                return ResourceManager.GetString("strDeploying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft .Net Framework 3.5 was not found, please download from this link: http://www.microsoft.com/downloads/details.aspx?FamilyId=333325FD-AE52-4E35-B531-508D977D32A6&amp;displaylang=en .
        /// </summary>
        internal static string strErrorNetFrameworkVersionNotFound {
            get {
                return ResourceManager.GetString("strErrorNetFrameworkVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Not all parameters were specified.\nProgram Usage: &apos;Installer.bat &lt;server&gt;:&lt;port&gt;&apos;.
        /// </summary>
        internal static string strErrorParameters {
            get {
                return ResourceManager.GetString("strErrorParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: SLK Version 1.3.1 is not installed.
        /// </summary>
        internal static string strErrorSLKNotInstaller {
            get {
                return ResourceManager.GetString("strErrorSLKNotInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLK version 1.3.1 was not found, please download from this link: http://www.codeplex.com/slk .
        /// </summary>
        internal static string strErrorSLKVersionNotFound {
            get {
                return ResourceManager.GetString("strErrorSLKVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  feature....
        /// </summary>
        internal static string strFeature {
            get {
                return ResourceManager.GetString("strFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string strGoingNewLine {
            get {
                return ResourceManager.GetString("strGoingNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is installed in your computer.
        /// </summary>
        internal static string strIsInstalled {
            get {
                return ResourceManager.GetString("strIsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft .Net Framework version .
        /// </summary>
        internal static string strNETVersion {
            get {
                return ResourceManager.GetString("strNETVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLK Version 1.3.1 is installed on your computer.
        /// </summary>
        internal static string strSLKInstalled {
            get {
                return ResourceManager.GetString("strSLKInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Solution was already deployed in .
        /// </summary>
        internal static string strSolutionAlreadyDeployed {
            get {
                return ResourceManager.GetString("strSolutionAlreadyDeployed", resourceCulture);
            }
        }
    }
}
